### ISSUE TITLE
schemaVersion no longer appearing in DataCite JSON format

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/lupo#347] opened 2019-10-10 09:02 UTC
### Expected Behaviour

schemaVersion listed in DataCite Json response

### Current Behaviour

In the "Datacite JSON" format, for some doi's there is no schemaVersion listed as a piece of data

### Steps to Reproduce

See example DOI: 10.18421/IJQR12.03-02

### Context (Environment)

API Production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_zgjn)

**Comment by adam3smith** [comment] 2019-11-22 16:05
Is there any update/expected timeline for a fix? 
I'd obviously love a quick fix, but a heads-up that this will remain broken for a longer would also help, so  we can look at workarounds for Zotero in the meantime.

**Comment by adam3smith** [comment] 2020-03-19 17:41
Hi folks - I realize this may not be the best time to bring this back up, but it continues to be a recurring annoyance at Zotero and we'd probably have to built in some hack-ish workaround unless this gets fixed. Is there any way you could give me a very rough idea on timing of fixing this? (like - ~3 days, ~3 weeks, ~3 months, not in the foreseeable future?)
I completely understand that bugs have different priority and this may not be anywhere near the top of your list, but getting some sense of that would be super helpful.

**Comment by mfenner** [comment] 2020-03-19 18:31
@adam3smith it is important to fix this. Given the current crazy times, it may take a bit of time. We will aim to resolve this by the end of April.

**Comment by adam3smith** [comment] 2020-03-19 19:07
Thanks @mfenner

**Comment by richardhallett** [comment] 2020-07-10 14:52
The underlying root cause was fixed a couple of months ago in a separate issue.
There are still potentially older DOIs that need updating however, this is being handled in #485

A work around for any DOIs that are problematic is to trigger an update for the DOI, this can be done through the APIs or via Fabrica.

Closing to keep conversations clear for what current issue is (i.e. older dois needing updating)

**Closed by richardhallett** 2020-07-10 14:52 UTC
Labels: bug
