### ISSUE TITLE
Citations count is inconsistent

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#576] opened 2020-07-03 13:05 UTC
### Expected Behaviour

Citations count should be the same when making queries or calling a resource

### Current Behaviour

Citations count is inconsistent between  /dois/10.XXX/xxx and /dois?doi=10.XXX/xxx 

### Steps to Reproduce

1. got to https://api.datacite.org/dois/10.5066/p9pyvpft
2. go to https://api.datacite.org/dois?query=10.5066/p9pyvpft
3. compare citation count

### Context (Environment)

The Count in the query response is consistent with the Events_index response.

/dois/10.XXX/xxx -> calls AR/DB
/dois?doi=10.XXX/xxx -> calls ES

### Hypothesis

When calling the AR/DB the calculation of the events its done on the flight by calling the events in the events table. 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nuvp)

**Comment by mfenner** [comment] 2020-07-11 09:31
Confirming the hypothesis. Updating the DOI triggers a reindex, which leads to a correct count in the query. The problem is probably that dois are not always properly updated when a new citation is added.

**Comment by mfenner** [comment] 2020-07-11 09:34
Duplicate of #577.

**Closed** 2020-07-11 09:35 UTC
Labels: bug, duplicate
