### ISSUE TITLE
Support queries for SICIs

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#180] opened 2019-01-04 14:53 UTC
## Error in Client API

**Elasticsearch::Transport::Transport::Errors::BadRequest** in **dois#index**
[400] {"error":{"root_cause":[{"type":"parse_exception","reason":"parse_exception: Encountered \" \":\" \": \"\" at line 1, column 40.\nWas expecting one of:\n    <EOF> \n    <AND> ...\n    <OR> ...\n    <NOT> ...\n    \"+\" ...\n    \"-\" ...\n    <BAREOPER> ...\n    \"(\" ...\n    \"*\" ...\n    \"^\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <FUZZY_SLOP> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    <REGEXPTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    "}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"dois","node":"OtjVznOmSrOamibi6fR6cA","reason":{"type":"query_shard_exception","reason":"Failed to parse query [10.1002\\/(SICI)1097-0355(199823)19:3<346::AID-IMHJ12>3.0.CO;2-X]","index_uuid":"FcfWy7PNSAWNf5hjFtWkMQ","index":"dois","caused_by":{"type":"parse_exception","reason":"parse_exception: Cannot parse '10.1002\\/(SICI)1097-0355(199823)19:3<346::AID-IMHJ12>3.0.CO;...

[View on Bugsnag](https://app.bugsnag.com/datacite/client-api/errors/5c2e26479ea15c0019d5b786?event_id=5c2f73250031f790d59d0000&i=gh&m=ci)

## Stacktrace

    app/controllers/dois_controller.rb:138 - index

[View full stacktrace](https://app.bugsnag.com/datacite/client-api/errors/5c2e26479ea15c0019d5b786?event_id=5c2f73250031f790d59d0000&i=gh&m=ci)

*Created by Martin Fenner via Bugsnag*

**Comment by mfenner** [comment] 2019-01-04 15:52
An error linked to this issue has been marked as fixed in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **dois#index**](https://app.bugsnag.com/datacite/client-api/errors/5c2e26479ea15c0019d5b786?event_id=5c2f8118003206f2f4ef0000&i=gh&m=fx)

**Comment by richardhallett** [comment] 2019-01-14 12:00
This is caused by elasticsearch query string options being present in the DOI pasted, it's not specifically related to SICI.
So the example: 10.1002/(SICI)1097-0355(199823)19:3<346::AID-IMHJ12>3.0.CO;2-X

This is failing because it needs to escape the ":" within the DOI.

However because this is part of the generic "query" we don't want to necessarily escape this by default because you may have a more complicated query in here.

**Comment by richardhallett** [comment] 2019-01-14 12:02
One potential solution is to switch over to using simple_query_string for requests made via our search forms. This will not then throw errors and if you want to use any more advanced query operators you have to explicitly escape them.

**Comment by richardhallett** [comment] 2019-01-16 08:33
@mfenner Your thoughts on this? It's not really a bug as such because the fact string put into the search could be anything and has to be escaped properly.
My solutions:

1) We switch to using simple_query_string for frontend interfaces i.e. fabrica - This removes lucene like search query but will not throw any errors and therefore wouldn't need as much escaping for the DOI's entered.

2) We can keep using query, but we have to accept that we will get errors from ES and potentially catch in the API and return something sensible to the user like "Unable to parse your search query, please format as appropriate". However I feel this is maybe not as user friendly, unless we document exactly how to use the search interfaces and what query syntax needs to be.

3) Another idea?

I'd go with 1 personally, we can still allow query via API, although I'd be also tempted to have a separate issue to do the handling of the errors nicer as opposed to in bugsnag.

**Comment by richardhallett** [comment] 2019-01-17 10:39
Discussing this more the main reasons we don't want to switch to simple query is that we want to allow the advanced syntax and in general this probably needs to be a bigger piece on how our new search and advanced search works, which is outside the scope of this bug.

The other problem is attempting to escape the potential characters in a DOI, while this might be possible if we know it's a DOI, this in fact is difficult with SICI as it already itself fails a lot of our common validation tests. 
Therefore this is not a simple scenario to fix, it is worth noting you can escape by using quotes around the DOI in question.

Therefore I'm going to mark as won't fix (or can't), until we can re-establish how fabrica search works when looking for DOI's.

**Closed by richardhallett** 2019-01-17 10:39 UTC
Labels: bug, bugsnag, development
