### ISSUE TITLE
ActionController::UnpermittedParameters in dois#update

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#179] opened 2019-01-04 12:10 UTC
## Error in Client API

**ActionController::UnpermittedParameters** in **dois#update**
found unpermitted parameter: :schemaOrgId

[View on Bugsnag](https://app.bugsnag.com/datacite/client-api/errors/5c2f2edbfb5d4e001cfb5393?event_id=5c2f4b430031fef559860000&i=gh&m=ci)

## Stacktrace

    app/controllers/dois_controller.rb:527 - safe_params
    app/controllers/dois_controller.rb:305 - update

[View full stacktrace](https://app.bugsnag.com/datacite/client-api/errors/5c2f2edbfb5d4e001cfb5393?event_id=5c2f4b430031fef559860000&i=gh&m=ci)

*Created by Martin Fenner via Bugsnag*

**Comment by richardhallett** [comment] 2019-01-04 15:49
The source bug of this was solved via https://github.com/datacite/pidcheck/issues/5
Work needs to be done to remove the offending data that is sat in the redis queue.

**Comment by richardhallett** [comment] 2019-01-11 17:18
CLosing as root caused solved. Some potential additional improvements need to be made to the storage lambda to ensure repeating failures isn't forever, this is handled under datacite/datacite#598

**Closed by richardhallett** 2019-01-11 17:18 UTC
Labels: bug, bugsnag, development
