### ISSUE TITLE
Media retrieval via API raises database error

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#466] opened 2020-04-14 09:43 UTC
GET to 
https://api.datacite.org/dois/10.22002/D1.1278/media
OR via MDS  https://mds.datacite.org/media/10.22002/D1.1278

Both return:

undefined method `page' for #<Media::ActiveRecord_AssociationRelation:0x0000561f0ad9cb58>"

**Comment by mfenner** [comment] 2020-04-17 17:51
Duplicate of datacite/poodle#33.

**Closed by mfenner** 2020-04-17 17:51 UTC
Labels: bug
