### ISSUE TITLE
Nokogiri::XML::SyntaxError in dois#update

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#89] opened 2018-07-18 10:27 UTC
## Error in Client API

**Nokogiri::XML::SyntaxError** in **dois#update**
330:0: ERROR: attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does not resolve to a(n) attribute declaration.

[View on Bugsnag](https://app.bugsnag.com/datacite/client-api/errors/5b286fb2dbd6270018a6fa06?event_id=5b4f0b378b7b5e0018ee316a&i=gh&m=ci)

## Stacktrace

    app/models/metadata.rb:53 - metadata_must_be_valid
    app/controllers/dois_controller.rb:190 - update

[View full stacktrace](https://app.bugsnag.com/datacite/client-api/errors/5b286fb2dbd6270018a6fa06?event_id=5b4f0b378b7b5e0018ee316a&i=gh&m=ci)

*Created by Kristian Garza via Bugsnag*

**Comment by kjgarza** [comment] 2018-07-18 10:30
On looking at this , I have comment. 
I found a bit odd that we are using Maremma to extract attributes from XML. 
example:
https://github.com/datacite/lupo/blob/bc1c72af8fef7b73576aac4f2c74571d6647aed0/app/models/doi.rb#L347

That's what its doing , right? is it fine if I change it (add a method in lupo that does the same)? I mean I always think MAremma is a http client to make calls, but here we are using differently

**Comment by mfenner** [comment] 2018-07-18 10:42
@kjgarza Please take a closer look at what `from_xml` in Maremma does, as this is special. I needed to overwrite the standard XML parsing function to add support for XML attributes. See https://github.com/datacite/maremma/blob/master/lib/maremma/xml_converter.rb

As we are monkey-patching the standard XML conversion, I preferred to do this in a single place to make that clear. While this could be extracted into a separate gem, that might be overkill.

**Comment by kjgarza** [comment] 2018-07-18 10:52
ok, let me look into that. 

> While this could be extracted into a separate gem, that might be overkill.

Well if the call had been using `Bolognese` I think it would have made more sense, to me, at first glance. I just saw `Maremma.from_xml` and my first reaction was "there is a HTTP request in here" .

Maybe i'm missing something else, but ok. I'll continue checking this. thanks

**Comment by mfenner** [comment] 2018-07-18 10:54
It is in `Maremma` because it automatically parses XML and JSON responses and turns them into a Ruby hash.

**Comment by kjgarza** [comment] 2018-07-19 08:30
as mentioned in 42db135 ,we cannot reproduce this problem. I think we should close it

**Comment by mfenner** [comment] 2018-07-19 08:33
@kjgarza sorry, I should have said that this error is usually caused by a network error fetching schema definitions, http://www.w3.org/XML/1998/namespace in this case.

**Closed** 2018-07-19 08:41 UTC
Labels: bug, bugsnag, needs review

**Comment by mfenner** [comment] 2018-07-20 01:48
An error linked to this issue has been reopened in Bugsnag
[**Nokogiri::XML::SyntaxError** in **dois#update**](https://app.bugsnag.com/datacite/client-api/errors/5b286fb2dbd6270018a6fa06?event_id=5b513f5200272820d5480000&i=gh&m=ra)
